In [73]:
# ques_1:

In [74]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [75]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64

In [76]:
# Part A


# Without using loops:

# Create a new array containing only values greater than 40.

idx = np.where(arr > 40)

ans = arr[idx]
ans

array([50, 60, 70, 80])

In [77]:
# Part B

# From the same array, return the indices where values are greater than 40.

idx

(array([4, 5, 6, 7]),)

In [78]:
# Part C
# Now interviewer says:

# "Good. Now replace all values greater than 40 with -1."

arr[arr > 40]=-1
arr

array([10, 20, 30, 40, -1, -1, -1, -1])

In [79]:
# Part D

# Now interviewer increases difficulty.

# Given:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

arr2 = np.array([100, 200, 300, 400])

# Append arr2 to arr:

# 1. Horizontally

# Expected:

# [10 20 30 40 50 60 70 80 100 200 300 400]

hor_st = np.hstack([arr, arr2])
print(hor_st)

# 2. Vertically
# np.vstack([arr, arr2])

# What error will occur?

# Why?
# both arrays are of different shape

# How will you fix it?
# make both arrays of same size and shape

[ 10  20  30  40  50  60  70  80 100 200 300 400]

In [80]:
# Part E (Real Interview Twist)

# Given:

arr = np.array([10,20,30,40,50,60,70,80])

# Return:

# [20,40,60,80]

ls=[]
for i in range(1, len(arr), 2):
    ls.append(int(arr[i]))
print(np.array(ls))
    
print(arr[1::2])

[20 40 60 80]
[20 40 60 80]

In [81]:
# Question 2: Customer Data Cleanup

In [82]:
import numpy as np

arr = np.array([
    "100",
    "200",
    "NA",
    "300",
    "NA",
    "500"
])

In [83]:
# Part A

# Find all positions where value is "NA".

print(np.where(arr=="NA"))

(array([2, 4]),)

In [84]:
# Part B

# Filter only valid numeric values.

# Expected:

# ['100' '200' '300' '500']

arr[arr!="NA"]

array(['100', '200', '300', '500'], dtype='<U3')

In [85]:
# Part C

# Convert filtered values to integers.

temp = arr[arr!="NA"]
print(temp)
print(type(temp))
print(temp.dtype)
print()

temp = temp.astype(int)
print(temp)
print(type(temp))
print(temp.dtype)

['100' '200' '300' '500']
<class 'numpy.ndarray'>
<U3

[100 200 300 500]
<class 'numpy.ndarray'>
int64

In [86]:
# Part D

# Replace all "NA" with "0".

# Expected:

# ['100' '200' '0' '300' '0' '500']

arr[arr=="NA"]="0"
arr

array(['100', '200', '0', '300', '0', '500'], dtype='<U3')

In [87]:
# Part E

# Calculate:

# sum
# mean
# max

# after conversion to integers.

print(temp.mean())
print(temp.sum())
print(temp.max())

275.0
1100
500

In [88]:
# Follow-up 2 (Important)

# Given:

arr = np.array([10,20,30,40,50])

# Output:

# [20,30,40]

# using:

# Boolean Masking
# arr[len(arr)-1]
# arr[ not arr[0] and not arr[len(arr)-1] ]
print(arr[(arr > 10) & (arr < 50)])

# Fancy Indexing

print(arr[[1,2,3]])

# Slicing
arr[1:len(arr)-1]

[20 30 40]
[20 30 40]

array([20, 30, 40])

In [89]:
# Follow-up 3 (Interview Trap)
arr = np.array([10,20,30])

b = arr.copy()

b[0] = 999

# What is:

print(arr)
print(b)

[10 20 30]
[999  20  30]

In [90]:
arr = np.array([10, 20, "Aman", 40, "Rahul", 50])
print(arr)

# shows error
# arr.astype(int)

['10' '20' 'Aman' '40' 'Rahul' '50']

In [91]:
import pandas as pd

ans = pd.to_numeric(arr, errors="coerce")
print(ans)
print(type(ans))
print(ans.dtype)

[10. 20. nan 40. nan 50.]
<class 'numpy.ndarray'>
float64

In [92]:
arr = np.array(["Aman Verma", "Nikhil Sharma", "Karan Bhola"])
print(arr)
print(type(arr))
print(arr.dtype)
print()

ans = np.char.split(arr, " ")
print(ans)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print()

ls = ans.tolist()
print(ls)
print(type(ls))
print()

pd.DataFrame(ans.tolist())

['Aman Verma' 'Nikhil Sharma' 'Karan Bhola']
<class 'numpy.ndarray'>
<U13

[list(['Aman', 'Verma']) list(['Nikhil', 'Sharma'])
 list(['Karan', 'Bhola'])]
<class 'numpy.ndarray'>
<U13
(3,)

[['Aman', 'Verma'], ['Nikhil', 'Sharma'], ['Karan', 'Bhola']]
<class 'list'>

        0       1
0    Aman   Verma
1  Nikhil  Sharma
2   Karan   Bhola

In [93]:
pd.DataFrame(ans)

                  0
0     [Aman, Verma]
1  [Nikhil, Sharma]
2    [Karan, Bhola]

In [94]:
# [12, 34, 56] -> it place values in a single dim as col. vertically!
# [[12, 34, 56]] -> its creates a dataframe of 2-d where values of list are put row wise

# so, numpy array of list -> was a single 1-d dim array, so thats way it create a dataframe without any 2 cols!
# we want to convert the values of arr array to list types, thats why we applied .tolist() method at there!

arr = np.array([[12, 34, 56]])
arr

array([[12, 34, 56]])

In [95]:
pd.DataFrame(arr)

    0   1   2
0  12  34  56

In [96]:
# Question 3: Salary Increment

In [97]:
import numpy as np

salary = np.array([50000, 60000, 70000, 80000])

In [98]:
# Part A

# Increase every salary by 10%.

# Expected:

# [55000. 66000. 77000. 88000.]

new_sal = salary + salary*0.10
new_sal

array([55000., 66000., 77000., 88000.])

In [99]:
# Part B

# Now each employee gets a different bonus:

bonus = np.array([5000, 3000, 2000, 1000])

# Add the bonus to salary.

sal_with_bns = salary + bonus
sal_with_bns

array([55000, 63000, 72000, 81000])

In [100]:
# Part C

# Predict output:

salary = np.array([
    [50000,60000],
    [70000,80000]
])

bonus = np.array([5000,1000])

salary + bonus

array([[55000, 61000],
       [75000, 81000]])

In [101]:
# Part D (Very Important)

# Predict:

salary = np.array([
    [50000,60000],
    [70000,80000]
])

bonus = np.array([
    [5000],
    [1000]
])

salary + bonus

array([[55000, 65000],
       [71000, 81000]])

In [102]:
# Follow-ups (5 Years DS Level)
# What is Broadcasting?
# When does broadcasting fail?
# Difference:
# reshape()
# ravel()
# flatten()
# Which creates a copy and which creates a view?

In [103]:
salary
print(salary)
print(id(salary))
print(type(salary))

[[50000 60000]
 [70000 80000]]
2500910367440
<class 'numpy.ndarray'>

In [104]:
vw = salary.view()
print(vw)
print(id(vw))
print(type(vw))

[[50000 60000]
 [70000 80000]]
2500869880976
<class 'numpy.ndarray'>

In [105]:
cp = salary.copy()
print(cp)
print(id(cp))
print(type(cp))

[[50000 60000]
 [70000 80000]]
2500912280272
<class 'numpy.ndarray'>

In [106]:
# View = shared memory, Copy = independent memory.

vw[1, 1] = 90000
print(vw)
print()
print(salary)

[[50000 60000]
 [70000 90000]]

[[50000 60000]
 [70000 90000]]

In [107]:
cp[1, 1] = 95000
print(cp)
print()
print(salary)

[[50000 60000]
 [70000 95000]]

[[50000 60000]
 [70000 90000]]

In [108]:
# Question 4: Customer Transaction Analysis

In [109]:
import numpy as np

txn = np.array([500, 200, 800, 200, 1000, 500, 300])

In [110]:
# Part A — where()

# Find positions where transaction amount is greater than 500.

# Expected:
# [2, 4]

idx = np.where(txn > 500)
txn[idx]

# Follow-up:
# Replace all transactions > 500 with 999.
txn[txn >500] = 999

In [111]:
txn

array([500, 200, 999, 200, 999, 500, 300])

In [112]:
# Part B — argmax()

# Without finding the value directly:

txn = np.array([500, 200, 800, 200, 1000, 500, 300])

# Find the index of the highest transaction.

print(np.argmax(txn))
print()

# Follow-up:
# How would you get the actual value using that index?
print(txn[np.argmax(txn)])

4

1000

In [113]:
# Part C — argsort() (Very Common)

# Find indices that would sort the array.

# Expected concept:
# np.argsort(txn)
sorted_txn = np.argsort(txn)
print(sorted_txn)
print(txn[sorted_txn])



# Follow-up:

# Get:

# Top 1 transaction
print(txn[sorted_txn][0])

# Top 3 transactions
print(txn[sorted_txn][:3])

# Top 3 transaction indices
print(sorted_txn[:3])

# Without using loops.

[1 3 6 0 5 2 4]
[ 200  200  300  500  500  800 1000]
200
[200 200 300]
[1 3 6]

In [116]:
# Part D — unique()

# Find all unique transaction values.

# Expected:
# [200, 300, 500, 800, 1000]

txn

array([ 500,  200,  800,  200, 1000,  500,  300])

In [120]:
np.unique( txn )

array([ 200,  300,  500,  800, 1000])

In [129]:
# Part E — isin() (Production Use Case)

# Suppose fraud transactions are:
fraud = [200, 1000]

# Return only fraud transactions from txn.
# Expected:
# [200, 200, 1000]

txn [ np.isin(txn, fraud) ]

array([ 200,  200, 1000])

In [130]:
# non fraud transactions

txn [~ np.isin(txn, fraud) ]

array([500, 800, 500, 300])

In [131]:
# Interview Twist (5 Years DS)

# Given:

txn = np.array([500, np.nan, 800, np.nan, 1000])
# What does:
np.max(txn)

# return?

# What should be used instead?
# Why?

np.float64(nan)

In [133]:
np.nanmax(txn)

np.float64(1000.0)

In [135]:
# copy, flatten, view, ravel, array, isin, where, astype, argmax, argmin, argsort, max, min, mean, sum, unique, nanmax, nanmin, nansum, nanamean

In [136]:
# Question 5: Customer Scores Analysis

In [137]:
import numpy as np

scores = np.array([
    [85, 92, 78],
    [90, 88, 95],
    [70, 60, 75],
    [95, 99, 98]
])

scores

array([[85, 92, 78],
       [90, 88, 95],
       [70, 60, 75],
       [95, 99, 98]])

In [138]:
scores.shape

(4, 3)

In [145]:
# Part A
# Find:
# Row-wise average
# Expected shape:
# (4,)

scores.mean(axis=1)

array([85.        , 91.        , 68.33333333, 97.33333333])

In [146]:
# Part B

# Find:

# Column-wise average

# Expected shape:

# (3,)


print(scores.mean(axis=0))
print(scores.mean(axis=0).shape)

[85.   84.75 86.5 ]
(3,)

In [149]:
# Part C

# Find index of student having highest average score.
scores.argmax()

np.int64(10)

In [152]:
# Part D
# Return students whose average score is greater than 85.
# (No loops)

# Hint:
# Boolean Masking

scores.mean(axis=0)

array([85.  , 84.75, 86.5 ])

In [155]:
scores [ scores.mean(axis=1) > 85 ]

array([[90, 88, 95],
       [95, 99, 98]])

In [156]:
# part E:
# add grace 5 marks to every studnet

scores + 5

array([[ 90,  97,  83],
       [ 95,  93, 100],
       [ 75,  65,  80],
       [100, 104, 103]])

In [158]:
# so, 

# scores > 45

# scores.mean(axis=1)

# both gives the values as True or False

# then, whatvre we want as True, so apply those things on scores to get the resuts from boolean ans.

In [159]:
# 6. Case Study: Customer Purchase Matrix

In [160]:
import numpy as np

sales = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900],
    [1000, 1100, 1200]
])

sales

# Rows = Customers
# Columns = Product Categories

array([[ 100,  200,  300],
       [ 400,  500,  600],
       [ 700,  800,  900],
       [1000, 1100, 1200]])

In [164]:
# Part A — Reshape vs Resize
# Q1

# Convert:

# (4,3)

# to

# (2,6)

# flatteing the numpy array
print(sales.reshape(-1))

print()

# chnaging shape of np array
print( sales.reshape(2,6))

[ 100  200  300  400  500  600  700  800  900 1000 1100 1200]

[[ 100  200  300  400  500  600]
 [ 700  800  900 1000 1100 1200]]

In [165]:
# reshape -> create a new array with new shape (like view)

# resize -> changes shape or size of original array

In [175]:
# Part B — Flatten vs Ravel
# Q2

sales = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900],
    [1000, 1100, 1200]
])

# Convert:

# (4,3)

# to

# (12,)

# flatening the array -> flatten -> create new array of flat dim
print(sales.flatten())
print()

# print(sales.ravel())
# print()

# sales[2] = 780
# print(sales)

# sales[2][1] = 890
# print(sales)

[ 100  200  300  400  500  600  700  800  900 1000 1100 1200]

In [176]:
# flatten -> create a deep copy; changes not reflect in original array, slow and memory consuming!

# ravel -> creates a reference (view) in memory; faster and efficient; changes not reflect in orginal array

In [179]:
# Part C — Transpose
# Q3

# Convert:

# (4,3)
print(sales)
print(sales.shape)
print()
# to

# (3,4)

print(sales.T)
print(sales.T.shape)

[[ 100  200  300]
 [ 400  500  600]
 [ 700  800  900]
 [1000 1100 1200]]
(4, 3)

[[ 100  400  700 1000]
 [ 200  500  800 1100]
 [ 300  600  900 1200]]
(3, 4)

In [181]:
# Part - D: Matrix Multiplications

weights = np.array([
    [0.2],
    [0.3],
    [0.5]
])

print(weights)

print()

print(sales.T * weights)

[[0.2]
 [0.3]
 [0.5]]

[[ 20.  80. 140. 200.]
 [ 60. 150. 240. 330.]
 [150. 300. 450. 600.]]

In [182]:
np.dot(sales, weights)

array([[ 230.],
       [ 530.],
       [ 830.],
       [1130.]])

In [183]:
sales @ weights

array([[ 230.],
       [ 530.],
       [ 830.],
       [1130.]])

In [ ]:
# replacing the zeros with a new value

In [184]:
data = np.array( [ 12, 34, 0, 23, 0, 11, 0, 0, 90, 0 ])
data

array([12, 34,  0, 23,  0, 11,  0,  0, 90,  0])

In [188]:
print(data)

data[data==0] = 100

[12 34  0 23  0 11  0  0 90  0]

In [189]:
data

array([ 12,  34, 100,  23, 100,  11, 100, 100,  90, 100])

In [190]:
# Random Numbers

In [191]:
np.random.randint(1000, 2000, size=10)

array([1490, 1572, 1309, 1067, 1119, 1748, 1925, 1356, 1979, 1502],
      dtype=int32)

In [193]:
np.random.rand(4,3)
np.random.rand(4)

array([0.03321918, 0.02174127, 0.62678643, 0.44923751])

In [194]:
np.random.uniform(1000, 2000, size=20)

array([1059.83280497, 1470.49179327, 1369.1476648 , 1907.70489599,
       1284.10788852, 1149.15781112, 1192.9645477 , 1324.83289416,
       1135.5165257 , 1114.21783225, 1586.97300419, 1035.0689897 ,
       1167.58302173, 1949.35193926, 1455.282628  , 1912.17118764,
       1517.29113296, 1646.66210388, 1403.6323634 , 1077.52547581])

In [195]:
cities = ["Delhi","Mumbai","Pune"]

np.random.choice(cities, size=5)

array(['Delhi', 'Delhi', 'Mumbai', 'Pune', 'Mumbai'], dtype='<U6')

In [196]:
np.random.normal(
    loc=50000,    # mean
    scale=10000,  # std dev
    size=100
)

array([53219.46748955, 47765.57309802, 36887.47695755, 34981.29543394,
       46388.3169062 , 75446.14411954, 50062.24747082, 50860.05798327,
       66324.55228042, 51825.38099005, 38215.61909512, 56336.08725197,
       44295.60900677, 55893.87080508, 45404.78624427, 69225.33393194,
       58862.72484938, 70212.48204398, 48037.47969958, 47708.18051229,
       58476.49129433, 47695.61434012, 38155.46679068, 61030.92012036,
       67438.6585722 , 56704.46326207, 49404.64290631, 58680.17921018,
       54182.08767645, 34269.58688108, 47794.26536499, 43403.15108427,
       71682.89078027, 41050.20529562, 39245.66876521, 45610.37316573,
       58372.05793545, 54328.37784758, 48689.45284305, 50097.23893633,
       53297.321546  , 73206.32806986, 43481.72827167, 59995.4235087 ,
       59335.2276485 , 49565.72752001, 41091.45493378, 40108.58309123,
       51732.84382764, 52250.30548116, 51940.47160809, 33863.32762488,
       44033.3028172 , 55751.74123535, 45735.35682669, 72638.44876594,
       38920.1079362 , 48089.82519623, 51272.56150058, 44953.06587309,
       45794.30960194, 60584.63979351, 47746.06074611, 41875.25855696,
       65337.12194081, 67995.41635959, 48209.61375796, 33512.12391449,
       72559.95453216, 49009.3181115 , 40551.16364443, 42544.96082171,
       60600.86752807, 52473.7183471 , 44121.65165615, 53087.20484228,
       54522.10839365, 30800.31422567, 43932.33541154, 58572.88637271,
       52254.16089894, 57482.57884652, 48117.76062511, 51317.46813301,
       38166.99754746, 55703.02250076, 63186.64781889, 69321.29377202,
       50507.00484073, 59503.42012692, 53448.21343983, 52203.45470578,
       50624.23481317, 41845.57149595, 69064.84448542, 55630.92269567,
       49094.12706997, 37224.13435585, 63221.64184412, 44908.06139079])

In [197]:
# Interview Case 1
# Create salary data for 40 employees

# Between 25k and 80k

np.random.randint(25000, 80001, size=40)

array([43246, 38497, 62665, 52615, 55839, 49885, 47124, 63840, 27253,
       28193, 78105, 30328, 41285, 44636, 54320, 28580, 28020, 48951,
       57364, 77927, 57497, 41836, 42892, 74782, 28595, 45077, 38580,
       60673, 63052, 26685, 63063, 43113, 37865, 49567, 27310, 67231,
       29695, 43481, 25634, 53724], dtype=int32)

In [198]:
# Interview Case 2
# Create employee ages

# Between 21 and 60

np.random.randint(21, 60, size=40)

array([39, 34, 28, 51, 47, 29, 30, 22, 30, 52, 23, 36, 47, 47, 56, 45, 40,
       50, 48, 31, 38, 27, 55, 50, 57, 42, 23, 45, 46, 26, 21, 22, 57, 28,
       52, 22, 38, 36, 52, 34], dtype=int32)

In [200]:
# Interview Case 3
# Create departments

np.random.choice(['HR', "Finance", "IT", "Marketing", "Sales"], size=8)

array(['Sales', 'HR', 'HR', 'IT', 'Finance', 'IT', 'Marketing', 'IT'],
      dtype='<U9')

In [203]:
# Interview Case 4
# Create gender column

np.random.choice(["Male", "Female"], size=10)

array(['Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Female'], dtype='<U6')

In [207]:
# Interview Case 5
# Create 40 rows × 5 features dataset

# np.random.rand(40, 5)
np.random.randint(1, 100, size=(40, 5))

array([[ 9, 15, 78,  8, 85],
       [59,  3, 65, 81, 36],
       [79,  7, 20, 23, 57],
       [63, 87, 38, 63,  8],
       [ 2, 52, 91, 28, 11],
       [61, 68, 78, 22, 15],
       [26, 26, 93, 70, 68],
       [73, 97, 52, 76, 92],
       [16, 62, 85, 98, 47],
       [91,  3, 19, 15, 84],
       [11, 13, 61, 96, 78],
       [69, 34, 76, 90, 50],
       [60, 62, 55, 94, 53],
       [19, 59, 44, 64, 60],
       [82, 60, 97, 38, 39],
       [74, 38, 59, 91, 25],
       [84, 72, 67, 10, 33],
       [63, 98, 91, 67, 77],
       [26, 52, 84, 43, 92],
       [89, 45, 25, 68, 11],
       [29, 44,  7, 26, 11],
       [73, 54, 67, 72, 15],
       [24,  2, 53, 64, 48],
       [98, 81, 18, 94, 42],
       [21, 85, 60, 27, 89],
       [95,  8, 81,  1, 76],
       [69, 64, 21, 44, 50],
       [41, 41, 92, 64, 96],
       [95, 74, 72, 54, 72],
       [ 9, 73, 17, 93, 24],
       [43, 74, 41, 63, 52],
       [95, 49, 45, 93, 18],
       [52, 86, 89, 50, 97],
       [12, 49, 37,  5, 94],
       [30, 67,  4,  8, 34],
       [21, 34,  1, 63, 29],
       [ 3, 81, 49, 57, 94],
       [79, 16, 52, 72, 99],
       [81, 16, 59, 18,  4],
       [74, 91, 60, 36, 53]], dtype=int32)

In [208]:
# Advanced Interview Case
# Create realistic salaries

# Instead of:

# np.random.randint(25000,80000,40)

salary = np.random.normal(
    loc=50000,
    scale=10000,
    size=40
)

In [209]:
salary

array([58165.22900922, 37374.81179601, 49684.6698329 , 39426.34229915,
       49207.05720661, 50368.72094854, 41182.51164948, 48527.6847347 ,
       49162.54744572, 57560.97123358, 44775.72874701, 41394.89471801,
       46464.67109244, 55929.92288747, 45041.11198725, 58648.87243395,
       39097.15712718, 47367.6771735 , 41068.85299599, 52485.73755576,
       46533.77535613, 69487.2460176 , 50882.70095101, 44691.45566677,
       33530.94077134, 16318.86597731, 48482.19434023, 52571.44335829,
       42394.17354424, 56716.77148499, 67038.68704746, 51111.77891976,
       43776.93895285, 41874.08669933, 59011.99965981, 46176.25688592,
       37166.37069683, 41766.95861518, 69627.97814876, 61028.805448  ])

In [212]:
# rand() → floats
# randint() → integers

In [213]:
# uniform() → all values equally likely
# normal() → bell-curve distribution

| Function                                  | Purpose                                         |
| ----------------------------------------- | ----------------------------------------------- |
| `np.random.seed(42)`                      | Fix randomness (reproducibility)                |
| `np.random.rand(5)`                       | Random floats between 0 and 1                   |
| `np.random.randn(5)`                      | Random values from standard normal distribution |
| `np.random.randint(10, 100, 5)`           | Random integers                                 |
| `np.random.uniform(1000, 5000, 5)`        | Random floats in a range                        |
| `np.random.normal(50000, 10000, 5)`       | Normal distribution (mean, std)                 |
| `np.random.choice([1,2,3], 5)`            | Random selection from values                    |
| `np.random.choice(arr, 5, replace=False)` | Random sample without replacement               |
| `np.random.shuffle(arr)`                  | Shuffle original array in-place                 |
| `np.random.permutation(arr)`              | Shuffled copy                                   |
| `np.random.random(5)`                     | Same as `rand()`, floats 0–1                    |
| `np.random.bytes(10)`                     | Random bytes (rarely used in DS)                |

Every time you run it, you'll get the same random numbers.

np.random.seed() makes random results reproducible, which is important for debugging, ML experiments, and model comparisons.

shuffle()      -> modifies original

permutation()  -> returns new shuffled array

In [1]:
# Case 1: E-commerce Conversion
conversion = np.random.binomial(
    n=1,
    p=0.15,
    # size=1000
)

NameError: name 'np' is not defined

In [ ]:
conversion.mean()