In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:\\Users\DELL\\Downloads\\TelecomCustomerChurn.csv")

In [3]:
data.head()

,customerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No,DSL,No,...,No,No,No,No,Monthly,Yes,Manual,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Manual,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Monthly,Yes,Manual,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Monthly,Yes,Manual,70.70,151.65,Yes

In [4]:
data.shape

(7043, 21)

In [5]:
data.ndim

2

In [6]:
data.index

RangeIndex(start=0, stop=7043, step=1)

In [7]:
df = data.copy()
df.shape

(7043, 21)

In [8]:
df.reset_index()

,index,customerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,No,DSL,...,No,No,No,No,Monthly,Yes,Manual,29.85,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,...,Yes,No,No,No,One year,No,Manual,56.95,1889.5,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,...,No,No,No,No,Monthly,Yes,Manual,53.85,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,No,DSL,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,...,No,No,No,No,Monthly,Yes,Manual,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,One year,Yes,Manual,84.80,1990.5,No
7039,7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No,DSL,...,No,No,No,No,Monthly,Yes,Manual,29.60,346.45,No
7041,7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,...,No,No,No,No,Monthly,Yes,Manual,74.40,306.6,Yes
7042,7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [9]:
(df.groupby('Gender')['Tenure'].mean().reset_index().rename(columns={"Tenure":"Avg Tenure"}).round(2)['Avg Tenure'] > 32.25).reset_index()

   index  Avg Tenure
0      0       False
1      1        True

In [10]:
df.groupby(['Gender', 'InternetService']).size()['Female', 'DSL']

np.int64(1188)

In [44]:
df.groupby(['Gender', 'InternetService']).size()

Gender  InternetService
Female  DSL                1188
        Fiber optic        1553
        No                  747
Male    DSL                1233
        Fiber optic        1543
        No                  779
dtype: int64

In [45]:
df.groupby(['Gender', 'InternetService']).size().index.tolist()

[('Female', 'DSL'),
 ('Female', 'Fiber optic'),
 ('Female', 'No'),
 ('Male', 'DSL'),
 ('Male', 'Fiber optic'),
 ('Male', 'No')]

In [46]:
df.groupby(['Gender', 'InternetService']).size().index.get_level_values("Gender").unique()

Index(['Female', 'Male'], dtype='object', name='Gender')

In [15]:
df.groupby(['Gender', 'InternetService']).size().reset_index()

   Gender InternetService     0
0  Female             DSL  1188
1  Female     Fiber optic  1553
2  Female              No   747
3    Male             DSL  1233
4    Male     Fiber optic  1543
5    Male              No   779

In [35]:
df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
)

                        Total_Tenure
Gender InternetService
Female DSL                     38993
       Fiber optic             50301
       No                      23175
Male   DSL                     40468
       Fiber optic             51613
       No                      23440

In [36]:
df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
).columns

Index(['Total_Tenure'], dtype='object')

In [37]:
df['TotalCharges'].dtype

dtype('O')

In [39]:
df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
).loc[('Female', 'DSL'), 'Total_Tenure']

np.int64(38993)

In [41]:
df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
).index.get_level_values("InternetService")

Index(['DSL', 'Fiber optic', 'No', 'DSL', 'Fiber optic', 'No'], dtype='object', name='InternetService')

In [47]:
df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
).loc['Female','DSL']

Total_Tenure    38993
Name: (Female, DSL), dtype: int64

In [49]:
ans = df.groupby(['Gender', 'InternetService']).agg(
    Total_Tenure=('Tenure', 'sum')
).reset_index()

In [51]:
ans[ans['Gender']=='Female']

   Gender InternetService  Total_Tenure
0  Female             DSL         38993
1  Female     Fiber optic         50301
2  Female              No         23175

In [52]:
ans

   Gender InternetService  Total_Tenure
0  Female             DSL         38993
1  Female     Fiber optic         50301
2  Female              No         23175
3    Male             DSL         40468
4    Male     Fiber optic         51613
5    Male              No         23440

In [55]:
ans.loc[1:4, 'Total_Tenure']

1    50301
2    23175
3    40468
4    51613
Name: Total_Tenure, dtype: int64

In [58]:
ans.loc[[1,3,5], 'Total_Tenure']

1    50301
3    40468
5    23440
Name: Total_Tenure, dtype: int64

In [61]:
ans.loc[ans['Gender']=='Female', 'Total_Tenure']

0    38993
1    50301
2    23175
Name: Total_Tenure, dtype: int64

In [65]:
ans.columns

Index(['Gender', 'InternetService', 'Total_Tenure'], dtype='object')

In [75]:
ans.set_index("InternetService").loc['DSL', 'Total_Tenure']

InternetService
DSL    38993
DSL    40468
Name: Total_Tenure, dtype: int64

In [77]:
ans.iloc[1:3, 0:2]

   Gender InternetService
1  Female     Fiber optic
2  Female              No

In [78]:
ans.columns

Index(['Gender', 'InternetService', 'Total_Tenure'], dtype='object')

In [79]:
ans[['Gender',  'Total_Tenure', 'InternetService']]

   Gender  Total_Tenure InternetService
0  Female         38993             DSL
1  Female         50301     Fiber optic
2  Female         23175              No
3    Male         40468             DSL
4    Male         51613     Fiber optic
5    Male         23440              No