***Interview Case Study #1***

In [25]:
import pandas as pd

df = pd.DataFrame({
    "emp_id":[1,2,3,4,5],
    "dept":["IT","HR","IT","Sales","HR"],
    "salary":[50000,40000,None,70000,45000],
    "age":[25,30,28,35,29]
})

df

   emp_id   dept   salary  age
0       1     IT  50000.0   25
1       2     HR  40000.0   30
2       3     IT      NaN   28
3       4  Sales  70000.0   35
4       5     HR  45000.0   29

In [26]:
# Q1

# Find employees with salary > 45000.

# Follow-up:

# Use loc
# Use query

df[ df['salary'] > 45000 ]

   emp_id   dept   salary  age
0       1     IT  50000.0   25
3       4  Sales  70000.0   35

In [27]:
df.loc[df['salary'] > 45000, ['emp_id', 'dept'] ]

   emp_id   dept
0       1     IT
3       4  Sales

In [28]:
df.query("salary > 45000")

   emp_id   dept   salary  age
0       1     IT  50000.0   25
3       4  Sales  70000.0   35

In [29]:
# Q2

# Find missing values.

# Follow-up:

# Fill with department-wise average salary.


df.isnull()

   emp_id   dept  salary    age
0   False  False   False  False
1   False  False   False  False
2   False  False    True  False
3   False  False   False  False
4   False  False   False  False

In [30]:
dept_wise_avg_sal = df.groupby(['dept'])['salary'].mean()
dept_wise_avg_sal

dept
HR       42500.0
IT       50000.0
Sales    70000.0
Name: salary, dtype: float64

In [31]:
# Follow-up: Fill with department-wise average salary
df['salary'] = df.groupby('dept')['salary'].transform(
    lambda x: x.fillna(x.mean())
)

In [32]:
df.isna()

   emp_id   dept  salary    age
0   False  False   False  False
1   False  False   False  False
2   False  False   False  False
3   False  False   False  False
4   False  False   False  False

In [33]:
df

   emp_id   dept   salary  age
0       1     IT  50000.0   25
1       2     HR  40000.0   30
2       3     IT  50000.0   28
3       4  Sales  70000.0   35
4       5     HR  45000.0   29

In [34]:
# Q3 ⭐

# Department-wise average salary.

df.groupby('dept')['salary'].mean()

dept
HR       42500.0
IT       50000.0
Sales    70000.0
Name: salary, dtype: float64

In [37]:
# Q4 ⭐⭐

# Find highest-paid employee in each department.

# df.groupby('dept')['salary'].idxmax()
df.loc[ df.groupby('dept')['salary'].idxmax() ]

   emp_id   dept   salary  age
4       5     HR  45000.0   29
0       1     IT  50000.0   25
3       4  Sales  70000.0   35

In [38]:
df.groupby('dept').apply(lambda x: x.nlargest(1, "salary"))

C:\Users\DELL\AppData\Local\Temp\ipykernel_10404\2532556045.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('dept').apply(lambda x: x.nlargest(1, "salary"))

         emp_id   dept   salary  age
dept
HR    4       5     HR  45000.0   29
IT    0       1     IT  50000.0   25
Sales 3       4  Sales  70000.0   35

In [ ]:
# Q5 ⭐⭐⭐

# Add column:

# salary_category

# Rules:

# <50000 -> Low
# 50000-60000 -> Medium
# >60000 -> High

In [39]:
df['salary_category'] = df['salary'].apply(lambda x: "Low" if x < 50000 else   "Medium" if (x >= 50000 and x <60000) else "High")
df

   emp_id   dept   salary  age salary_category
0       1     IT  50000.0   25          Medium
1       2     HR  40000.0   30             Low
2       3     IT  50000.0   28          Medium
3       4  Sales  70000.0   35            High
4       5     HR  45000.0   29             Low

In [43]:
pd.cut(df['salary'], 
    bins=[0, 50000, 60000, float("inf")],
    labels=['Low', "Medium", "High"])

0     Low
1     Low
2     Low
3    High
4     Low
Name: salary, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [47]:
# Q6 ⭐⭐⭐

# Create:

# dept_summary

# containing:

# dept
# employee_count
# avg_salary
# max_salary

df.groupby('dept').agg(employee_count=("emp_id", "size"), avg_salary=("salary", "mean"), max_salary=("salary", "max"))

       employee_count  avg_salary  max_salary
dept
HR                  2     42500.0     45000.0
IT                  2     50000.0     50000.0
Sales               1     70000.0     70000.0

In [48]:
import pandas as pd

customers = pd.DataFrame({
    "cust_id":[101,102,103,104,105,106],
    "customer_name":["Aman","Nikhil","Karan","Rahul","Priya","Neha"],
    "city":["Delhi","Mumbai","Delhi","Pune","Mumbai","Bangalore"]
})

orders = pd.DataFrame({
    "order_id":[1,2,3,4,5,6,7,8],
    "cust_id":[101,102,101,103,107,104,102,108],
    "amount":[500,1200,800,300,1500,700,1000,900],
    "category":["Electronics","Fashion","Fashion","Grocery",
                "Electronics","Fashion","Grocery","Fashion"]
})

In [49]:
# Q1 (Warm-up)

# Merge both tables.

df = customers.copy()

df.merge(orders, on="cust_id", how="outer")

   cust_id customer_name       city  order_id  amount     category
0      101          Aman      Delhi       1.0   500.0  Electronics
1      101          Aman      Delhi       3.0   800.0      Fashion
2      102        Nikhil     Mumbai       2.0  1200.0      Fashion
3      102        Nikhil     Mumbai       7.0  1000.0      Grocery
4      103         Karan      Delhi       4.0   300.0      Grocery
5      104         Rahul       Pune       6.0   700.0      Fashion
6      105         Priya     Mumbai       NaN     NaN          NaN
7      106          Neha  Bangalore       NaN     NaN          NaN
8      107           NaN        NaN       5.0  1500.0  Electronics
9      108           NaN        NaN       8.0   900.0      Fashion

In [52]:
# Q2 (Real Business Question)

# Find orders whose customer information is missing.

df.merge(orders, on="cust_id", how="right").query("customer_name.isnull()")

   cust_id customer_name city  order_id  amount     category
4      107           NaN  NaN         5    1500  Electronics
7      108           NaN  NaN         8     900      Fashion

In [54]:
merged = df.merge(orders, on="cust_id", how="right")
missing_info = merged[merged["customer_name"].isnull()]
missing_info

   cust_id customer_name city  order_id  amount     category
4      107           NaN  NaN         5    1500  Electronics
7      108           NaN  NaN         8     900      Fashion

In [57]:
# Q3 (Frequently Asked)

# Find customers who never placed any order.

df.merge(orders, on='cust_id', how='left').query("order_id.isnull()")

   cust_id customer_name       city  order_id  amount category
6      105         Priya     Mumbai       NaN     NaN      NaN
7      106          Neha  Bangalore       NaN     NaN      NaN

In [58]:
merged_df = df.merge(orders, on="cust_id", how="left")
merged_df[ merged_df['order_id'].isnull() ]

   cust_id customer_name       city  order_id  amount category
6      105         Priya     Mumbai       NaN     NaN      NaN
7      106          Neha  Bangalore       NaN     NaN      NaN

In [61]:
# Q4 (Product Company Level)

# City-wise analysis:

# Return:

# city	total_orders	total_revenue

merged_df = df.merge(orders, on='cust_id', how="outer")
merged_df

   cust_id customer_name       city  order_id  amount     category
0      101          Aman      Delhi       1.0   500.0  Electronics
1      101          Aman      Delhi       3.0   800.0      Fashion
2      102        Nikhil     Mumbai       2.0  1200.0      Fashion
3      102        Nikhil     Mumbai       7.0  1000.0      Grocery
4      103         Karan      Delhi       4.0   300.0      Grocery
5      104         Rahul       Pune       6.0   700.0      Fashion
6      105         Priya     Mumbai       NaN     NaN          NaN
7      106          Neha  Bangalore       NaN     NaN          NaN
8      107           NaN        NaN       5.0  1500.0  Electronics
9      108           NaN        NaN       8.0   900.0      Fashion

In [64]:
merged_df.groupby('city').agg(total_orders = ("order_id", "count"), revenue=("amount", "sum"))

           total_orders  revenue
city
Bangalore             0      0.0
Delhi                 3   1600.0
Mumbai                2   2200.0
Pune                  1    700.0

In [66]:
# Q5 (Good 5-Year Question)

# Category-wise:

# Total Revenue
# Average Revenue
# Number of Orders

merged_df.groupby("category").agg(revenue=("amount", "sum"), avg_revenue=("amount", "mean"), number_of_orders=("order_id", "count"))

             revenue  avg_revenue  number_of_orders
category
Electronics   2000.0       1000.0                 2
Fashion       3600.0        900.0                 4
Grocery       1300.0        650.0                 2

In [78]:
# Q6 (Very Common)

# Find Top 3 customers by revenue.

# Expected output:

# cust_id	revenue
# Follow-up

# Return customer name as well.

result = merged_df.groupby('cust_id')['amount'].sum().reset_index()[:3]
result

   cust_id  amount
0      101  1300.0
1      102  2200.0
2      103   300.0

In [86]:
# result.cust_id.isin(customers['cust_id'])

result.merge(customers, on="cust_id", how="left")[['customer_name', 'amount', 'cust_id']]

  customer_name  amount  cust_id
0          Aman  1300.0      101
1        Nikhil  2200.0      102
2         Karan   300.0      103

In [91]:
# Q7 (Strong Candidate Question)

# For each city:

# Find customer who generated maximum revenue.

# (No loops)


# simple and easy soln
merged_df.groupby(['city', 'cust_id'])['amount'].sum().reset_index()\
.sort_values(["city","amount"], ascending=[True,False])\
.groupby('city').head(1)

        city  cust_id  amount
0  Bangalore      106     0.0
1      Delhi      101  1300.0
3     Mumbai      102  2200.0
5       Pune      104   700.0

In [93]:
# For each city: customer with max revenue
max_rev = (
    merged_df.groupby(["city","cust_id"])["amount"].sum().reset_index()
)

result = max_rev.loc[max_rev.groupby("city")["amount"].idxmax()]
result

        city  cust_id  amount
0  Bangalore      106     0.0
1      Delhi      101  1300.0
3     Mumbai      102  2200.0
5       Pune      104   700.0

In [95]:
# Q8 (Interview Twist)

# Suppose:

orders["amount"] = [500,None,800,300,None,700,1000,900]

# Now:

# Calculate city revenue.
# Ignore missing values properly.
# Follow-up

# Should you use:

# mean
# median
# zero
# for imputation?

# Why?

result = customers.merge(orders, on='cust_id', how="outer")

In [97]:
result.groupby('city')['amount'].sum(min_count=1)

city
Bangalore       NaN
Delhi        1600.0
Mumbai       1000.0
Pune          700.0
Name: amount, dtype: float64